### PR TITLE
I added some of my customer's site. Please kindly review

### PR DESCRIPTION
**Pull request by somsak**
Don't sure if the site listed in blocked.json must be the origin or the video streaming backend, so I added both. Tested in my laptop.

### CODE REVIEW

**Comment by somsak** [comment]
@chandler-stimson Is there anything other thing I need to do first before accepting this merge request?

**Comment by chandler-stimson** [comment]
To ensure protection against misuse, moving forward, I will require an email from the owner of the website.

**Comment by somsak** [comment]
Ok, do you just want email or do you need the person to reply in this comment?

The owner of the content is operating www.ch3plus.com, which own the content in Thailand.

**Comment by chandler-stimson** [comment]
I have already approved your merge request. No additional steps are needed for this one.

> Ok, do you just want email or do you need the person to reply in this comment?

I require an email confirming the authorization of the pull request. Just to double-check the merge is actually requested by the owner.

**Pull request merged**
